### ISSUE TITLE
How  does your model work  in a scene without pocket-ligand complex conformation?

### ISSUE THREAD

**Issue by yinliangying** [smiles724/ProtMD#1]
Thank you for your excellent work .   Your work presents a good way to get pocket-ligand complex representation using little  MD trajectories data. And  your paper presents a good result on binding activity prediction in PDBbind dataset. There exists a question that how does your model work  in a scene  without complex structure conformations , such as the HTS(high throughput screening) ？Does your model need docking data when using as a HTS screener?

**Comment by smiles724** [comment]
Thanks for your praise. Yes, as you said, our model requires complex structure conformations. Thus, you may need to dock the ligand and the protein. However, as the additional results we implemented in our paper if you have the structure of the receptor protein. You can use some machine-learning approaches such as Equibind, Tankbind, DiffDock to obtain the docking structures without even the need to know the ligand structure. But please note that our model performs a little bit worse on these predicted structures rather than on experimental structures. 

Hope this helps.

**Comment by microbenh** [comment]
If use traditional docking or AI based docking, there maybe several different complex conformation,  so the model may pred several affinitity results, how to deal with such problem?

**Comment by smiles724** [comment]
> If use traditional docking or AI based docking, there maybe several different complex conformation, so the model may pred several affinitity results, how to deal with such problem?

This is a really good question and deserves further discussion. Actually, in the paper, we examine our ProtMD model on the predicted binding structure docked by EquiBind, and it shows convincing robustness. 

However, we have to admit that different complex conformations would be given different predictions for the same protein-ligand pair. But according to our limited experiments on EquiBind's docking results, the variance would not be large. Thus, we propose that taking a mean average of several affinity predictions may be a choice. But we are uncertain its effectiveness.
